// Dependency-free local bridge: receives Figma variables + styles from the plugin UI
// and writes them into the repo as CSS. Run: `npm run figma:bridge`.

import { createServer } from "node:http";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const PORT = 3999;
const HERE = dirname(fileURLToPath(import.meta.url));
const CONSOLE_ROOT = resolve(HERE, "../../.."); // apps/console
const REPO_ROOT = resolve(CONSOLE_ROOT, "../.."); // repo root
const OUT_FILE = resolve(CONSOLE_ROOT, "app/tokens.css");
const DEBUG_FILE = resolve(HERE, "..", ".last-payload.json");
const EXPORT_DIR = resolve(CONSOLE_ROOT, "tools/figma-export/out");
const SHOTS_DIR = resolve(EXPORT_DIR, "screenshots");
const rel = (p) => relative(REPO_ROOT, p);

const slug = (...parts) =>
  parts
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const round = (n) => Math.round(n * 1000) / 1000;

function hexToRgba(hex, a) {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${round(a)})`;
}
const color = ({ hex, a }) => (a < 1 ? hexToRgba(hex, a) : hex);

// Figma FLOAT variables carry no unit. Opacity tokens are stored as 0-100 → CSS 0-1;
// everything else is treated as a pixel length.
function renderFloat(name, value) {
  if (/opacity|alpha/i.test(name)) return String(value > 1 ? round(value / 100) : value);
  return `${value}px`;
}

function renderValue(name, v) {
  if (!v) return null;
  switch (v.kind) {
    case "COLOR":
      return color(v);
    case "FLOAT":
      return renderFloat(name, v.value);
    case "ALIAS":
      return `var(--${slug(v.refCollection, v.refName)})`;
    case "STRING":
      return `"${v.value}"`;
    case "BOOLEAN":
      return String(v.value);
    default:
      return String(v.value);
  }
}

function fmtLineHeight(lh) {
  if (!lh || lh.unit === "AUTO") return "normal";
  return lh.unit === "PERCENT" ? `${round(lh.value)}%` : `${round(lh.value)}px`;
}
function fmtLetterSpacing(ls) {
  if (!ls || !ls.value) return "normal";
  return ls.unit === "PERCENT" ? `${round(ls.value / 100)}em` : `${round(ls.value)}px`;
}
const WEIGHTS = {
  thin: 100, extralight: 200, ultralight: 200, light: 300, regular: 400, normal: 400,
  medium: 500, semibold: 600, demibold: 600, bold: 700, extrabold: 800, ultrabold: 800, black: 900, heavy: 900
};
function fontWeight(style) {
  const key = style.toLowerCase().replace(/italic/g, "").replace(/\s+/g, "");
  return WEIGHTS[key] || 400;
}
const isItalic = (style) => /italic/i.test(style);

function shadowCss(shadows) {
  return shadows
    .map((s) => `${s.inset ? "inset " : ""}${s.x}px ${s.y}px ${s.blur}px ${s.spread}px ${color(s.color)}`)
    .join(", ");
}

function buildCss(payload) {
  const root = [];
  const modeBlocks = new Map();

  for (const c of payload.collections || []) {
    for (const v of c.variables) {
      const name = `--${slug(c.name, v.name)}`;
      for (const [modeId, val] of Object.entries(v.valuesByMode)) {
        const cv = renderValue(v.name, val);
        if (cv == null) continue;
        if (modeId === c.defaultModeId) {
          root.push(`  ${name}: ${cv};`);
        } else {
          const mode = c.modes.find((m) => m.modeId === modeId);
          const key = mode ? mode.name : modeId;
          if (!modeBlocks.has(key)) modeBlocks.set(key, []);
          modeBlocks.get(key).push(`  ${name}: ${cv};`);
        }
      }
    }
  }

  const styles = payload.styles || { text: [], paint: [], effect: [] };
  // Paint styles are intentionally skipped — in this file they duplicate the primitive
  // color variables 1:1, so emitting them would just add noise.
  for (const e of styles.effect || []) {
    if (e.shadows && e.shadows.length) root.push(`  --shadow-${slug(e.name)}: ${shadowCss(e.shadows)};`);
  }

  let out =
    `/* AUTO-GENERATED by tools/figma-tokens — do not edit by hand.\n` +
    `   Source: Figma file "${payload.fileName}". Regenerate via the plugin + \`npm run figma:bridge\`. */\n\n`;
  out += `:root {\n${root.join("\n")}\n}\n`;
  for (const [mode, lines] of modeBlocks) {
    out += `\n[data-theme="${slug(mode)}"] {\n${lines.join("\n")}\n}\n`;
  }

  if (styles.text && styles.text.length) {
    out += `\n/* Typography — Figma text styles */\n`;
    for (const t of styles.text) {
      out +=
        `.text-${slug(t.name)} {\n` +
        `  font-family: "${t.fontFamily}";\n` +
        `  font-size: ${t.fontSize}px;\n` +
        `  line-height: ${fmtLineHeight(t.lineHeight)};\n` +
        `  letter-spacing: ${fmtLetterSpacing(t.letterSpacing)};\n` +
        `  font-weight: ${fontWeight(t.fontStyle)};\n` +
        (isItalic(t.fontStyle) ? `  font-style: italic;\n` : ``) +
        `}\n`;
    }
  }
  return out;
}

// ---- token-aware HTML/CSS generator (draft) ------------------------------

const escapeHtml = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
const tokenVar = (ref) => `var(--${slug(ref)})`;

function paintCss(paints) {
  if (!Array.isArray(paints)) return null;
  const solid = paints.find((p) => p.type === "SOLID" && !p.hidden);
  if (solid) return solid.variable ? tokenVar(solid.variable) : color(solid);
  const grad = paints.find((p) => typeof p.type === "string" && p.type.indexOf("GRADIENT") === 0);
  if (grad && grad.stops) return `linear-gradient(${grad.stops.map((s) => `${color(s)} ${Math.round(s.pos * 100)}%`).join(", ")})`;
  return null;
}
function radiusCss(o) {
  if (o.radiusVar) return tokenVar(o.radiusVar);
  if (typeof o.radius === "number") return `${o.radius}px`;
  if (o.radius) return `${o.radius.tl}px ${o.radius.tr}px ${o.radius.br}px ${o.radius.bl}px`;
  return null;
}
const JUST = { MIN: "flex-start", CENTER: "center", MAX: "flex-end", SPACE_BETWEEN: "space-between" };
const ALIGN = { MIN: "flex-start", CENTER: "center", MAX: "flex-end", BASELINE: "baseline" };

function genNode(node, rules, seq, abs) {
  if (node.hidden) return ""; // don't render layers hidden in Figma
  const cls = `n-${slug(node.name) || "node"}-${seq.i++}`;
  const s = [];
  if (abs) s.push("position:absolute", `left:${node.x || 0}px`, `top:${node.y || 0}px`);
  if (node.layout) {
    const L = node.layout;
    s.push("display:flex", `flex-direction:${L.dir === "VERTICAL" ? "column" : "row"}`);
    if (L.wrap === "WRAP") s.push("flex-wrap:wrap");
    if (L.gap) s.push(`gap:${L.boundSpacing && L.boundSpacing.itemSpacing ? tokenVar(L.boundSpacing.itemSpacing) : L.gap + "px"}`);
    if (L.pad) s.push(`padding:${L.pad.t}px ${L.pad.r}px ${L.pad.b}px ${L.pad.l}px`);
    if (L.primary) s.push(`justify-content:${JUST[L.primary] || "flex-start"}`);
    if (L.counter) s.push(`align-items:${ALIGN[L.counter] || "stretch"}`);
  }
  if (node.sizing) {
    if (node.sizing.h === "FIXED" && node.w) s.push(`width:${node.w}px`);
    if (node.sizing.v === "FIXED" && node.h) s.push(`height:${node.h}px`);
    if (node.sizing.h === "FILL") s.push("align-self:stretch", "flex:1 1 0");
  } else if (typeof node.w === "number" && node.type !== "TEXT") {
    s.push(`width:${node.w}px`, `height:${node.h}px`);
  }
  const r = radiusCss(node);
  if (r) s.push(`border-radius:${r}`);
  if (node.strokes) {
    const sc = paintCss(node.strokes);
    if (sc) s.push(`border:${node.strokeWeight || 1}px solid ${sc}`);
  }
  if (typeof node.opacity === "number") s.push(`opacity:${node.opacity}`);
  if (node.clip) s.push("overflow:hidden");
  if (node.effects) {
    const sh = node.effects
      .filter((e) => e.type === "DROP_SHADOW" || e.type === "INNER_SHADOW")
      .map((e) => `${e.type === "INNER_SHADOW" ? "inset " : ""}${e.offset.x}px ${e.offset.y}px ${e.radius}px ${e.spread || 0}px ${e.color ? color(e.color) : "#0000"}`)
      .join(", ");
    if (sh) s.push(`box-shadow:${sh}`);
  }

  if (node.image) {
    const mime = node.image.format === "svg" ? "image/svg+xml" : "image/png";
    rules.push(`.${cls}{${s.join(";")}}`);
    return `<img class="${cls}" src="data:${mime};base64,${node.image.base64}" alt="${escapeHtml(node.name)}" />`;
  }

  if (node.type === "TEXT") {
    const fg = paintCss(node.fills);
    if (fg) s.push(`color:${fg}`);
    if (!node.textStyle) {
      if (node.fontSize) s.push(`font-size:${node.fontSize}px`);
      if (node.font) s.push(`font-family:"${node.font.family}"`);
    }
    if (node.textAlign && node.textAlign !== "LEFT") s.push(`text-align:${node.textAlign.toLowerCase()}`);
    if (abs && node.autoResize === "NONE" && node.w) s.push(`width:${node.w}px`);
    else if (abs) s.push("white-space:nowrap");
    rules.push(`.${cls}{${s.join(";")}}`);
    const tc = node.textStyle ? ` text-${slug(node.textStyle)}` : "";
    return `<span class="${cls}${tc}">${escapeHtml(node.text || "")}</span>`;
  }

  const bg = paintCss(node.fills);
  if (bg) s.push(`background:${bg}`);
  if (node.bgImage) {
    const bsize = { FILL: "cover", FIT: "contain", CROP: "cover", TILE: "auto" }[node.bgImage.scaleMode] || "cover";
    s.push(
      `background-image:url(data:image/png;base64,${node.bgImage.base64})`,
      `background-size:${bsize}`,
      "background-position:center",
      node.bgImage.scaleMode === "TILE" ? "background-repeat:repeat" : "background-repeat:no-repeat"
    );
  }
  // Frames without auto-layout: position children absolutely by their Figma x/y.
  const childAbs = !node.layout && Array.isArray(node.children) && node.children.length > 0;
  if (childAbs) s.push("position:relative");
  rules.push(`.${cls}{${s.join(";")}}`);
  const inner = (node.children || []).map((c) => genNode(c, rules, seq, childAbs)).join("");
  return `<div class="${cls}">${inner}</div>`;
}

function structureToHtml(structure, title) {
  const rules = [];
  const body = genNode(structure, rules, { i: 0 });
  return (
    `<!doctype html>\n<html lang="ko">\n<head>\n<meta charset="utf-8" />\n<title>${escapeHtml(title)}</title>\n` +
    `<!-- Draft auto-generated from Figma. Tokens referenced via var(--...) resolve against app/tokens.css. -->\n` +
    `<link rel="stylesheet" href="../../../app/tokens.css" />\n` +
    `<style>\nbody{margin:0;padding:24px;background:#0b0b0c}\n${rules.join("\n")}\n</style>\n</head>\n<body>\n${body}\n</body>\n</html>\n`
  );
}

async function handleExport(payload, res) {
  await mkdir(SHOTS_DIR, { recursive: true });
  const written = [];
  for (const node of payload.nodes || []) {
    const name = slug(node.name || "node");
    const jsonNoBlobs = JSON.stringify(node.structure, (k, v) => (k === "base64" ? `<${v.length}b>` : v), 2);
    await writeFile(resolve(EXPORT_DIR, `${name}.json`), jsonNoBlobs, "utf8");
    await writeFile(resolve(EXPORT_DIR, `${name}.html`), structureToHtml(node.structure, node.name || name), "utf8");
    if (node.png) await writeFile(resolve(SHOTS_DIR, `${name}.png`), Buffer.from(node.png, "base64"));
    written.push(name);
  }
  console.log(`✓ export: ${written.join(", ")} → ${rel(EXPORT_DIR)} (json + html + png)`);
  res.writeHead(200, { "Content-Type": "application/json" }).end(JSON.stringify({ ok: true, nodes: written, dir: rel(EXPORT_DIR) }));
}

const server = createServer((req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return void res.writeHead(204).end();
  if (req.method !== "POST" || !(req.url.startsWith("/tokens") || req.url.startsWith("/export"))) {
    return void res.writeHead(404, { "Content-Type": "application/json" }).end(JSON.stringify({ error: "not found" }));
  }
  let body = "";
  req.on("data", (chunk) => (body += chunk));
  req.on("end", async () => {
    try {
      const payload = JSON.parse(body);
      if (req.url.startsWith("/export")) return void (await handleExport(payload, res));
      await mkdir(dirname(OUT_FILE), { recursive: true });
      await writeFile(OUT_FILE, buildCss(payload), "utf8");
      await writeFile(DEBUG_FILE, JSON.stringify(payload, null, 2), "utf8");

      const vars = (payload.collections || []).reduce((n, c) => n + c.variables.length, 0);
      const s = payload.styles || { text: [], paint: [], effect: [] };
      const total = vars + s.text.length + s.paint.length + s.effect.length;

      console.log(`\n✓ ${rel(OUT_FILE)}`);
      for (const c of payload.meta ? payload.meta.collections : []) {
        console.log(`  collection "${c.name}"  modes=[${c.modes.join(", ")}]  vars=${c.variables}`);
      }
      console.log(`  text=${s.text.length}  paint=${s.paint.length}  effect=${s.effect.length}  → debug: ${rel(DEBUG_FILE)}`);

      res.writeHead(200, { "Content-Type": "application/json" }).end(
        JSON.stringify({ ok: true, variables: vars, text: s.text.length, paint: s.paint.length, effect: s.effect.length, total, path: rel(OUT_FILE) })
      );
    } catch (err) {
      res.writeHead(400, { "Content-Type": "application/json" }).end(JSON.stringify({ error: String(err.message || err) }));
      console.error("✗", err);
    }
  });
});

server.listen(PORT, () => console.log(`figma-tokens bridge on http://localhost:${PORT}  → writes ${rel(OUT_FILE)}`));
