// Dependency-free local bridge: receives Figma variables + styles from the plugin UI
// and writes them into the repo as CSS. Run: `npm run figma:bridge`.

import { createServer } from "node:http";
import { writeFile, mkdir, rm } from "node:fs/promises";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const PORT = 3999;
const HERE = dirname(fileURLToPath(import.meta.url));
const CONSOLE_ROOT = resolve(HERE, "../../.."); // apps/console
const REPO_ROOT = resolve(CONSOLE_ROOT, "../.."); // repo root
// 기획서 10.7: the primitives ship as their own workspace package so docs, reports and the
// console share one palette. fonts.css stays in the app — only the tokens moved.
const OUT_FILE = resolve(REPO_ROOT, "packages/design-tokens/tokens.css");
const DEBUG_FILE = resolve(HERE, "..", ".last-payload.json");
const EXPORT_DIR = resolve(CONSOLE_ROOT, "tools/figma-export/out");
// apps/console sits three levels above out/ (out → figma-export → tools → apps/console),
// which is where fonts.css lives; the tokens package is two more levels up at the repo root.
const CONSOLE_DEPTH = 3;
const TOKENS_PREFIX = "../../packages/design-tokens/";
const rel = (p) => relative(REPO_ROOT, p);

// CSS identifiers stay ASCII — they become custom-property names in tokens.css and must keep
// matching what theme.css references.
const slug = (...parts) =>
  parts
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

// File and folder names keep Hangul. Stripping it collapses distinct Korean frame names into
// the same slug ("SCR-101 게이트웨이" and "SCR-101 정책" both became "scr-101"), and a purely
// Korean name slugged to nothing at all.
const FILE_UNSAFE = /[^a-z0-9가-힣ᄀ-ᇿ㄰-㆏]+/g;
const fileSlug = (name) =>
  String(name)
    .normalize("NFC")
    .toLowerCase()
    .replace(FILE_UNSAFE, "-")
    .replace(/^-+|-+$/g, "");

const round = (n) => Math.round(n * 1000) / 1000;

function hexToRgba(hex, a) {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${round(a)})`;
}
const color = ({ hex, a }) => (a < 1 ? hexToRgba(hex, a) : hex);

// Figma FLOAT variables carry no unit. Opacity tokens are stored as 0-100 → CSS 0-1;
// everything else is treated as a pixel length.
function renderFloat(name, value) {
  if (/opacity|alpha/i.test(name)) return String(value > 1 ? round(value / 100) : value);
  return `${value}px`;
}

function renderValue(name, v) {
  if (!v) return null;
  switch (v.kind) {
    case "COLOR":
      return color(v);
    case "FLOAT":
      return renderFloat(name, v.value);
    case "ALIAS":
      return `var(--${slug(v.refCollection, v.refName)})`;
    case "STRING":
      return `"${v.value}"`;
    case "BOOLEAN":
      return String(v.value);
    default:
      return String(v.value);
  }
}

function fmtLineHeight(lh) {
  if (!lh || lh.unit === "AUTO") return "normal";
  return lh.unit === "PERCENT" ? `${round(lh.value)}%` : `${round(lh.value)}px`;
}
function fmtLetterSpacing(ls) {
  if (!ls || !ls.value) return "normal";
  return ls.unit === "PERCENT" ? `${round(ls.value / 100)}em` : `${round(ls.value)}px`;
}
const WEIGHTS = {
  thin: 100, extralight: 200, ultralight: 200, light: 300, regular: 400, normal: 400,
  medium: 500, semibold: 600, demibold: 600, bold: 700, extrabold: 800, ultrabold: 800, black: 900, heavy: 900
};
function fontWeight(style) {
  const key = style.toLowerCase().replace(/italic/g, "").replace(/\s+/g, "");
  return WEIGHTS[key] || 400;
}
const isItalic = (style) => /italic/i.test(style);

function shadowCss(shadows) {
  return shadows
    .map((s) => `${s.inset ? "inset " : ""}${s.x}px ${s.y}px ${s.blur}px ${s.spread}px ${color(s.color)}`)
    .join(", ");
}

function buildCss(payload) {
  const root = [];
  const modeBlocks = new Map();

  for (const c of payload.collections || []) {
    for (const v of c.variables) {
      const name = `--${slug(c.name, v.name)}`;
      for (const [modeId, val] of Object.entries(v.valuesByMode)) {
        const cv = renderValue(v.name, val);
        if (cv == null) continue;
        if (modeId === c.defaultModeId) {
          root.push(`  ${name}: ${cv};`);
        } else {
          const mode = c.modes.find((m) => m.modeId === modeId);
          const key = mode ? mode.name : modeId;
          if (!modeBlocks.has(key)) modeBlocks.set(key, []);
          modeBlocks.get(key).push(`  ${name}: ${cv};`);
        }
      }
    }
  }

  const styles = payload.styles || { text: [], paint: [], effect: [] };
  // Paint styles are intentionally skipped — in this file they duplicate the primitive
  // color variables 1:1, so emitting them would just add noise.
  for (const e of styles.effect || []) {
    if (e.shadows && e.shadows.length) root.push(`  --shadow-${slug(e.name)}: ${shadowCss(e.shadows)};`);
  }

  let out =
    `/* AUTO-GENERATED by tools/figma-tokens — do not edit by hand.\n` +
    `   Source: Figma file "${payload.fileName}". Regenerate via the plugin + \`npm run figma:bridge\`. */\n\n`;
  out += `:root {\n${root.join("\n")}\n}\n`;
  for (const [mode, lines] of modeBlocks) {
    out += `\n[data-theme="${slug(mode)}"] {\n${lines.join("\n")}\n}\n`;
  }

  if (styles.text && styles.text.length) {
    out += `\n/* Typography — Figma text styles */\n`;
    for (const t of styles.text) {
      out +=
        `.text-${slug(t.name)} {\n` +
        `  font-family: "${t.fontFamily}";\n` +
        `  font-size: ${t.fontSize}px;\n` +
        `  line-height: ${fmtLineHeight(t.lineHeight)};\n` +
        `  letter-spacing: ${fmtLetterSpacing(t.letterSpacing)};\n` +
        `  font-weight: ${fontWeight(t.fontStyle)};\n` +
        (isItalic(t.fontStyle) ? `  font-style: italic;\n` : ``) +
        `}\n`;
    }
  }
  return out;
}

// ---- token-aware HTML/CSS generator (draft) ------------------------------

const escapeHtml = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
const tokenVar = (ref) => `var(--${slug(ref)})`;

function paintCss(paints) {
  if (!Array.isArray(paints)) return null;
  const solid = paints.find((p) => p.type === "SOLID" && !p.hidden);
  if (solid) return solid.variable ? tokenVar(solid.variable) : color(solid);
  const grad = paints.find((p) => typeof p.type === "string" && p.type.indexOf("GRADIENT") === 0);
  if (grad && grad.stops) return `linear-gradient(${grad.stops.map((s) => `${color(s)} ${Math.round(s.pos * 100)}%`).join(", ")})`;
  return null;
}
function radiusCss(o) {
  if (o.radiusVar) return tokenVar(o.radiusVar);
  if (typeof o.radius === "number") return `${o.radius}px`;
  if (o.radius) return `${o.radius.tl}px ${o.radius.tr}px ${o.radius.br}px ${o.radius.bl}px`;
  return null;
}
const JUST = { MIN: "flex-start", CENTER: "center", MAX: "flex-end", SPACE_BETWEEN: "space-between" };
const ALIGN = { MIN: "flex-start", CENTER: "center", MAX: "flex-end", BASELINE: "baseline" };

function genNode(node, rules, seq, abs, parentDir) {
  if (node.hidden) return ""; // don't render layers hidden in Figma
  const cls = `n-${slug(node.name) || "node"}-${seq.i++}`;
  const s = [];
  if (abs) s.push("position:absolute", `left:${node.x || 0}px`, `top:${node.y || 0}px`);
  // An icon exported as one SVG already contains its own padding and alignment. Re-applying the
  // frame's padding to the <img> shrinks the artwork into the content box (border-box), which is
  // how a 40px badge ends up drawing at 24px.
  if (node.layout && !node.image) {
    const L = node.layout;
    s.push("display:flex", `flex-direction:${L.dir === "VERTICAL" ? "column" : "row"}`);
    if (L.wrap === "WRAP") s.push("flex-wrap:wrap");
    if (L.gap) s.push(`gap:${L.boundSpacing && L.boundSpacing.itemSpacing ? tokenVar(L.boundSpacing.itemSpacing) : L.gap + "px"}`);
    if (L.pad) s.push(`padding:${L.pad.t}px ${L.pad.r}px ${L.pad.b}px ${L.pad.l}px`);
    if (L.primary) s.push(`justify-content:${JUST[L.primary] || "flex-start"}`);
    if (L.counter) s.push(`align-items:${ALIGN[L.counter] || "stretch"}`);
  }
  if (node.sizing) {
    if (node.sizing.h === "FIXED" && node.w) s.push(`width:${node.w}px`);
    if (node.sizing.v === "FIXED" && node.h) s.push(`height:${node.h}px`);
    // A frame set to HUG with nothing inside it has nothing to hug, so CSS collapses it to its
    // padding — an emptied component instance loses its whole height. Figma still measured the
    // size it was drawn at (via a min-size or the instance's own bounds); hold that as a floor.
    // Never for text: pinning a run to the width Figma measured would mask a missing font
    // instead of letting the mismatch show.
    if (node.type !== "TEXT" && !node.image && !(node.children || []).length) {
      if (node.sizing.h === "HUG" && node.w) s.push(`min-width:${node.w}px`);
      if (node.sizing.v === "HUG" && node.h) s.push(`min-height:${node.h}px`);
    }
    // FILL means "fill the parent", but which CSS property does that depends on the parent's
    // direction: flex-grow along its main axis, align-self across it. Emitting both (or the
    // wrong one) makes every child of a column stretch to full height and the layout collapses.
    const fillMain = parentDir === "VERTICAL" ? node.sizing.v : node.sizing.h;
    const fillCross = parentDir === "VERTICAL" ? node.sizing.h : node.sizing.v;
    if (parentDir) {
      if (fillMain === "FILL") s.push("flex:1 1 0");
      if (fillCross === "FILL") s.push("align-self:stretch");
    } else {
      if (node.sizing.h === "FILL") s.push("width:100%");
      if (node.sizing.v === "FILL") s.push("height:100%");
    }
    // A run Figma set to HUG grows with its own content and never wraps. In CSS it is just another
    // flex item, so it can be squeezed down to its automatic minimum — and that minimum breaks
    // after a hyphen, which is how `#s-0712` came out of the draft as `#s-` over `0712` when the
    // design has it on one line. Forbid the squeeze rather than pin the width the way the frames
    // do above: at `flex:none` the run measures itself, so a missing font still shows up as an
    // overflow instead of being hidden inside a box held open at Figma's number.
    if (node.type === "TEXT") {
      if (node.sizing.h === "HUG") {
        s.push("white-space:nowrap");
        if (parentDir === "HORIZONTAL") s.push("flex:none");
      }
      // A FILL run is meant to wrap inside the width its parent hands it. Its automatic minimum
      // would floor it at min-content instead and push its siblings out of the row.
      if (node.sizing.h === "FILL" && parentDir) s.push("min-width:0");
    }
  } else if (typeof node.w === "number" && node.type !== "TEXT") {
    s.push(`width:${node.w}px`, `height:${node.h}px`);
  }
  const r = radiusCss(node);
  if (r) s.push(`border-radius:${r}`);
  else if (node.type === "ELLIPSE") s.push("border-radius:50%");
  // Strokes and effects share `box-shadow`, so they have to be emitted together — declaring
  // it twice silently drops whichever came first.
  const shadows = [];
  // Not for image nodes: Figma's SVG export already draws their fill and stroke. Emitting the
  // stroke again as CSS wraps a rectangle around the artwork — an arrow ends up in a box.
  if (node.strokes && !node.image) {
    const sc = paintCss(node.strokes);
    const sides = node.strokeSides;
    const weight = node.strokeWeight || 1;
    const inset = node.strokeAlign === "OUTSIDE" ? "" : "inset ";
    // Figma's default INSIDE stroke is painted within the frame; a CSS border grows the box
    // instead, which is a 2px error on every bordered element. A ring shadow does not.
    if (!sc) {
      /* no visible stroke paint */
    } else if (sides && new Set(Object.values(sides)).size > 1) {
      // Sides differ — usually a single divider rule. One shadow per side keeps it that way.
      const OFFSET = { top: [0, 1], bottom: [0, -1], left: [1, 0], right: [-1, 0] };
      for (const [side, w] of Object.entries(sides)) {
        if (!w || !OFFSET[side]) continue;
        const [x, y] = OFFSET[side];
        shadows.push(`${inset}${x * w}px ${y * w}px 0 0 ${sc}`);
      }
    } else if (node.strokeAlign === "CENTER") {
      s.push(`border:${weight}px solid ${sc}`);
    } else {
      shadows.push(`${inset}0 0 0 ${weight}px ${sc}`);
    }
  }
  if (typeof node.opacity === "number") s.push(`opacity:${node.opacity}`);
  if (node.clip) s.push("overflow:hidden");
  if (node.effects) {
    for (const e of node.effects) {
      if (e.type !== "DROP_SHADOW" && e.type !== "INNER_SHADOW") continue;
      shadows.push(
        `${e.type === "INNER_SHADOW" ? "inset " : ""}${e.offset.x}px ${e.offset.y}px ${e.radius}px ${e.spread || 0}px ${e.color ? color(e.color) : "#0000"}`
      );
    }
  }
  if (shadows.length) s.push(`box-shadow:${shadows.join(", ")}`);

  if (node.image) {
    const mime = node.image.format === "svg" ? "image/svg+xml" : "image/png";
    // An icon in a flex row is shrunk by the browser unless it is told not to; and an SVG
    // exported at its own size must not be re-stretched by a FILL rule above.
    s.push("flex:none", "object-fit:contain");
    if (typeof node.w === "number" && !s.some((d) => d.startsWith("width:")))
      s.push(`width:${node.w}px`, `height:${node.h}px`);
    rules.push(`.${cls}{${s.join(";")}}`);
    return `<img class="${cls}" src="data:${mime};base64,${node.image.base64}" alt="${escapeHtml(node.name)}" />`;
  }

  if (node.type === "TEXT") {
    const fg = paintCss(node.fills);
    if (fg) s.push(`color:${fg}`);
    if (!node.textStyle) {
      if (node.fontSize) s.push(`font-size:${node.fontSize}px`);
      if (node.font) {
        s.push(`font-family:"${node.font.family}"`);
        // Without these three the draft renders every label at 400 weight and the browser's
        // default leading, which is where most of the vertical drift against the design comes from.
        s.push(`font-weight:${fontWeight(node.font.style)}`);
        if (isItalic(node.font.style)) s.push("font-style:italic");
      }
      const lh = fmtLineHeight(node.lineHeight);
      if (lh !== "normal") s.push(`line-height:${lh}`);
      const ls = fmtLetterSpacing(node.letterSpacing);
      if (ls !== "normal") s.push(`letter-spacing:${ls}`);
    }
    if (node.textAlign && node.textAlign !== "LEFT") s.push(`text-align:${node.textAlign.toLowerCase()}`);
    if (abs && node.autoResize === "NONE" && node.w) s.push(`width:${node.w}px`);
    else if (abs) s.push("white-space:nowrap");
    rules.push(`.${cls}{${s.join(";")}}`);
    const tc = node.textStyle ? ` text-${slug(node.textStyle)}` : "";
    // Per-character colours arrive as segments; each becomes its own coloured span.
    if (Array.isArray(node.segments) && node.segments.length > 1) {
      const inner = node.segments
        .map((seg) => {
          const c = paintCss(seg.fills);
          return c ? `<span style="color:${c}">${escapeHtml(seg.text)}</span>` : escapeHtml(seg.text);
        })
        .join("");
      return `<span class="${cls}${tc}">${inner}</span>`;
    }
    return `<span class="${cls}${tc}">${escapeHtml(node.text || "")}</span>`;
  }

  const bg = paintCss(node.fills);
  if (bg) s.push(`background:${bg}`);
  if (node.bgImage) {
    const bsize = { FILL: "cover", FIT: "contain", CROP: "cover", TILE: "auto" }[node.bgImage.scaleMode] || "cover";
    s.push(
      `background-image:url(data:image/png;base64,${node.bgImage.base64})`,
      `background-size:${bsize}`,
      "background-position:center",
      node.bgImage.scaleMode === "TILE" ? "background-repeat:repeat" : "background-repeat:no-repeat"
    );
  }
  // Frames without auto-layout: position children absolutely by their Figma x/y.
  const childAbs = !node.layout && Array.isArray(node.children) && node.children.length > 0;
  if (childAbs) s.push("position:relative");
  rules.push(`.${cls}{${s.join(";")}}`);
  const inner = (node.children || [])
    .map((c) => genNode(c, rules, seq, childAbs, node.layout ? node.layout.dir : null))
    .join("");
  return `<div class="${cls}">${inner}</div>`;
}

function structureToHtml(structure, title, depth) {
  const rules = [];
  const body = genNode(structure, rules, { i: 0 });
  const up = "../".repeat(CONSOLE_DEPTH + depth);
  return (
    `<!doctype html>\n<html lang="ko">\n<head>\n<meta charset="utf-8" />\n<title>${escapeHtml(title)}</title>\n` +
    `<!-- Draft auto-generated from Figma. Tokens referenced via var(--...) resolve against packages/design-tokens/tokens.css. -->\n` +
    // fonts.css carries the @font-face rules. Without it every draft silently falls back to a
    // system font, so nothing the design measured — text width, and any box hugging it — lines up.
    `<link rel="stylesheet" href="${up}app/fonts.css" />\n` +
    `<link rel="stylesheet" href="${up}${TOKENS_PREFIX}tokens.css" />\n` +
    // border-box: Figma's widths already include padding and stroke, so the browser default
    // (content-box) inflates every fixed-size frame that has either.
    // No body padding: the frame has to start at 0,0 so the draft can be laid over the .png
    // next to it. A viewing gutter here shifts every coordinate and hides real misalignment.
    `<style>\n*{box-sizing:border-box}\nbody{margin:0;background:#0b0b0c}\n${rules.join("\n")}\n</style>\n</head>\n<body>\n${body}\n</body>\n</html>\n`
  );
}

// ---- section-scoped export (streamed one item per request) ----------------

let exportRun = { written: [], taken: new Map() };

// Figma names are attacker-adjacent input for the filesystem: keep only slugged segments.
const safeSegments = (path) => (Array.isArray(path) ? path : []).map((p) => fileSlug(p)).filter(Boolean);

// Two frames can still legitimately share a name inside one folder. Number the later ones
// rather than overwriting, and say so — a silent overwrite looks like a missing export.
function claimName(dirKey, base) {
  const used = exportRun.taken.get(dirKey) || new Set();
  let name = base;
  for (let n = 2; used.has(name); n++) name = `${base}-${n}`;
  used.add(name);
  exportRun.taken.set(dirKey, used);
  return name;
}

async function handleBegin(payload, res) {
  exportRun = { written: [], taken: new Map() };
  const roots = safeSegments(payload.roots);
  for (const root of roots) await rm(resolve(EXPORT_DIR, root), { recursive: true, force: true });
  await mkdir(EXPORT_DIR, { recursive: true });
  console.log(`\n▸ export "${payload.fileName || "?"}" → ${rel(EXPORT_DIR)}`);
  if (roots.length) console.log(`  cleared: ${roots.join(", ")}`);
  res.writeHead(200, { "Content-Type": "application/json" }).end(JSON.stringify({ ok: true, cleared: roots }));
}

async function handleItem(item, res) {
  const segments = safeSegments(item.path);
  const base = fileSlug(item.name || "") || "node";
  const name = claimName(segments.join("/"), base);
  // Every item owns a folder, so it can be wiped wholesale without touching its siblings —
  // this also cleans up loose items at the root, which /begin never clears.
  const dir = resolve(EXPORT_DIR, ...segments, name);
  await rm(dir, { recursive: true, force: true });
  await mkdir(dir, { recursive: true });

  const jsonNoBlobs = JSON.stringify(item.structure, (k, v) => (k === "base64" ? `<${v.length}b>` : v), 2);
  await writeFile(resolve(dir, `${name}.json`), jsonNoBlobs, "utf8");
  await writeFile(resolve(dir, `${name}.html`), structureToHtml(item.structure, item.name || name, segments.length + 1), "utf8");
  if (item.png) await writeFile(resolve(dir, `${name}.png`), Buffer.from(item.png, "base64"));

  const shown = segments.concat([name, ""]).join("/");
  exportRun.written.push(shown);
  const renamed = name !== base ? `  ⚠ "${item.name}" collides with an earlier export` : "";
  console.log(`  ✓ ${shown}${item.png ? "" : "  (no png)"}${renamed}`);
  res.writeHead(200, { "Content-Type": "application/json" }).end(JSON.stringify({ ok: true, path: shown }));
}

async function handleTokens(payload, res) {
  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, buildCss(payload), "utf8");
  await writeFile(DEBUG_FILE, JSON.stringify(payload, null, 2), "utf8");

  const vars = (payload.collections || []).reduce((n, c) => n + c.variables.length, 0);
  const s = payload.styles || { text: [], paint: [], effect: [] };
  const total = vars + s.text.length + s.paint.length + s.effect.length;

  console.log(`\n✓ ${rel(OUT_FILE)}`);
  for (const c of payload.meta ? payload.meta.collections : []) {
    console.log(`  collection "${c.name}"  modes=[${c.modes.join(", ")}]  vars=${c.variables}`);
  }
  console.log(`  text=${s.text.length}  paint=${s.paint.length}  effect=${s.effect.length}  → debug: ${rel(DEBUG_FILE)}`);

  res.writeHead(200, { "Content-Type": "application/json" }).end(
    JSON.stringify({ ok: true, variables: vars, text: s.text.length, paint: s.paint.length, effect: s.effect.length, total, path: rel(OUT_FILE) })
  );
}

async function handleDone(payload, res) {
  const written = exportRun.written.length;
  const missing = (payload.total || written) - written;
  console.log(`✓ ${written} item(s) → ${rel(EXPORT_DIR)}${missing > 0 ? `  (${missing} failed)` : ""}`);
  res.writeHead(200, { "Content-Type": "application/json" }).end(JSON.stringify({ ok: true, written, dir: rel(EXPORT_DIR) }));
}

const server = createServer((req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return void res.writeHead(204).end();
  // Exact routes only: an unmatched path must never fall through to the tokens writer,
  // which would clobber packages/design-tokens/tokens.css with whatever body it was handed.
  const route = (req.url || "").split("?")[0].replace(/\/+$/, "");
  const HANDLERS = {
    "/tokens": handleTokens,
    "/export/begin": handleBegin,
    "/export/item": handleItem,
    "/export/done": handleDone,
  };
  const handler = req.method === "POST" ? HANDLERS[route] : undefined;
  if (!handler) {
    return void res
      .writeHead(404, { "Content-Type": "application/json" })
      .end(JSON.stringify({ error: `not found: ${req.method} ${route}` }));
  }
  let body = "";
  req.on("data", (chunk) => (body += chunk));
  req.on("end", async () => {
    try {
      await handler(JSON.parse(body), res);
    } catch (err) {
      res.writeHead(400, { "Content-Type": "application/json" }).end(JSON.stringify({ error: String(err.message || err) }));
      console.error("✗", err);
    }
  });
});

server.listen(PORT, () => console.log(`figma-tokens bridge on http://localhost:${PORT}  → writes ${rel(OUT_FILE)}`));
