// Generated by scripts/compile-runtime-policies.ts. Do not edit by hand.
import type { Action, EvaluationStrategy, Policy } from "@guardmcp/policy-engine";

export interface RuntimePolicyPack {
  defaultAction: Action;
  evaluationStrategy: EvaluationStrategy;
  extends: string[];
  policies: Policy[];
}

export const runtimePolicyPacks: Record<string, RuntimePolicyPack> = {
  "author-retest": {
    "defaultAction": "allow",
    "evaluationStrategy": "severity-max",
    "extends": [],
    "policies": [
      {
        "id": "author_retest_block_limited_fetch_obfuscated_injection",
        "pack": "author-retest",
        "version": 1,
        "description": "Block very high-risk obfuscated injection in limited-server fetch responses",
        "priority": 105,
        "match": {
          "direction": "response",
          "tool": "fetch_url",
          "server_trust": "limited",
          "detections": {
            "any_of": [
              "INJECTION.OBFUSCATED"
            ]
          },
          "risk_score": {
            "gte": 90
          }
        },
        "action": "block",
        "severity": "high",
        "message": "A very high-risk obfuscated injection response was blocked by policy."
      }
    ]
  },
  "author-test": {
    "defaultAction": "allow",
    "evaluationStrategy": "severity-max",
    "extends": [],
    "policies": [
      {
        "id": "author_test_block_obfuscated_injection_fetch_response",
        "pack": "author-test",
        "version": 1,
        "description": "Block high-risk obfuscated injection in fetch_url responses from untrusted servers",
        "priority": 100,
        "match": {
          "direction": "response",
          "tool": "fetch_url",
          "server_trust": "untrusted",
          "detections": {
            "any_of": [
              "INJECTION.OBFUSCATED"
            ]
          },
          "risk_score": {
            "gte": 80
          }
        },
        "action": "block",
        "severity": "high",
        "message": "A high-risk obfuscated injection response was blocked by policy."
      }
    ]
  },
  "default": {
    "defaultAction": "allow",
    "evaluationStrategy": "severity-max",
    "extends": [],
    "policies": [
      {
        "id": "block_env_file_read",
        "pack": "default",
        "version": 1,
        "description": "Block reads of credential-bearing files",
        "priority": 100,
        "match": {
          "direction": "request",
          "tool": "read_file",
          "server_trust": "any",
          "args": {
            "path_regex": "(^|/)(\\.env(\\..*)?|id_(rsa|ed25519)|credentials(\\.json)?)$"
          }
        },
        "action": "block",
        "severity": "critical",
        "message": "Credential-file access was blocked by policy.",
        "reasonCode": "SECRET_FILE_ACCESS_BLOCKED"
      },
      {
        "id": "block_untrusted_injection_response",
        "pack": "default",
        "version": 1,
        "description": "Block high-risk prompt injection returned by an untrusted MCP server",
        "priority": 120,
        "match": {
          "direction": "response",
          "tool": "*",
          "server_trust": "untrusted",
          "detections": {
            "any_of": [
              "INJECTION",
              "INJECTION.INDIRECT",
              "INJECTION.OBFUSCATED"
            ]
          },
          "risk_score": {
            "gte": 90
          }
        },
        "action": "block",
        "severity": "critical",
        "message": "Tool output was blocked because it matched a high-risk injection policy.",
        "reasonCode": "PROMPT_INJECTION_DETECTED"
      },
      {
        "id": "warn_injection_request",
        "pack": "default",
        "version": 1,
        "description": "Warn on prompt-injection wording in tool arguments instead of blocking it",
        "priority": 130,
        "match": {
          "direction": "request",
          "tool": "*",
          "server_trust": "any",
          "detections": {
            "any_of": [
              "INJECTION",
              "INJECTION.INDIRECT",
              "INJECTION.OBFUSCATED"
            ]
          },
          "risk_score": {
            "gte": 40
          }
        },
        "action": "warn",
        "severity": "medium",
        "message": "Prompt-injection wording was detected in the tool arguments and recorded."
      },
      {
        "id": "approve_external_email_with_secret",
        "pack": "default",
        "version": 1,
        "description": "Require human approval before sending sensitive data outside the organization",
        "priority": 200,
        "match": {
          "direction": "request",
          "tool": "send_email",
          "server_trust": "any",
          "args": {
            "to_not_domain": [
              "company.co.kr"
            ]
          },
          "detections": {
            "any_of": [
              "SECRET",
              "PII.RRN_LIKE"
            ]
          },
          "risk_score": {
            "gte": 70
          }
        },
        "action": "require_approval",
        "severity": "high",
        "approval": {
          "timeout_seconds": 120,
          "on_timeout": "block",
          "allow_masked_approval": true
        },
        "message": "External transmission is waiting for human approval."
      },
      {
        "id": "mask_secret_response",
        "pack": "default",
        "version": 1,
        "description": "Mask credentials detected in MCP tool responses",
        "priority": 310,
        "match": {
          "direction": "response",
          "tool": "*",
          "server_trust": "any",
          "detections": {
            "any_of": [
              "SECRET"
            ]
          }
        },
        "action": "mask_then_allow",
        "severity": "high",
        "message": "Credential spans were masked before the tool response was delivered."
      },
      {
        "id": "require_approval_untrusted_high_risk_tool",
        "pack": "default",
        "version": 1,
        "description": "신뢰 등급이 untrusted인 서버로 향하는 고위험 Tool 호출은 사람 승인을 거친다",
        "priority": 150,
        "match": {
          "direction": "request",
          "tool": "send_*",
          "server_trust": "untrusted"
        },
        "action": "require_approval",
        "severity": "high",
        "approval": {
          "timeout_seconds": 120,
          "on_timeout": "block",
          "allow_masked_approval": false
        },
        "message": "미검증(untrusted) 서버로 향하는 고위험 도구 호출은 승인이 필요합니다."
      }
    ]
  },
  "korean-pii": {
    "defaultAction": "allow",
    "evaluationStrategy": "severity-max",
    "extends": [
      "default@^1.0.0"
    ],
    "policies": [
      {
        "id": "mask_korean_pii_response",
        "pack": "korean-pii",
        "version": 1,
        "description": "Mask Korean PII detected in MCP tool responses",
        "priority": 300,
        "match": {
          "direction": "response",
          "tool": "*",
          "server_trust": "any",
          "detections": {
            "any_of": [
              "PII"
            ]
          }
        },
        "action": "mask_then_allow",
        "severity": "high",
        "message": "Personal-data spans were masked before the tool response was delivered."
      },
      {
        "id": "approve_external_email_with_korean_pii",
        "pack": "korean-pii",
        "version": 1,
        "description": "Require approval before emailing Korean PII outside the organization",
        "priority": 180,
        "match": {
          "direction": "request",
          "tool": "send_email",
          "server_trust": "any",
          "args": {
            "to_not_domain": [
              "company.co.kr"
            ]
          },
          "detections": {
            "any_of": [
              "PII"
            ]
          },
          "risk_score": {
            "gte": 70
          }
        },
        "action": "require_approval",
        "severity": "high",
        "approval": {
          "timeout_seconds": 120,
          "on_timeout": "block",
          "allow_masked_approval": true
        },
        "message": "Sending personal data outside the organization requires approval."
      }
    ]
  }
};
