import { readFile, readdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { parse } from "yaml";

interface Manifest {
  name: string;
  default_action: string;
  evaluation_strategy: string;
  extends?: string[];
  policies: string[];
}

const root = resolve("policy-packs");
const output = resolve("packages/gateway/src/policies.generated.ts");
const packs: Record<string, unknown> = {};

for (const entry of (await readdir(root, { withFileTypes: true })).filter((candidate) => candidate.isDirectory()).sort((left, right) => left.name.localeCompare(right.name))) {
  const packRoot = join(root, entry.name);
  const manifest = parse(await readFile(join(packRoot, "pack.yaml"), "utf8")) as Manifest;
  const policies = await Promise.all(manifest.policies.map(async (path) => parse(await readFile(join(packRoot, path), "utf8"))));
  packs[manifest.name] = {
    defaultAction: manifest.default_action,
    evaluationStrategy: manifest.evaluation_strategy,
    extends: manifest.extends ?? [],
    policies
  };
}

const source = `// Generated by scripts/compile-runtime-policies.ts. Do not edit by hand.\n`
  + `import type { Action, EvaluationStrategy, Policy } from "@guardmcp/policy-engine";\n\n`
  + `export interface RuntimePolicyPack {\n  defaultAction: Action;\n  evaluationStrategy: EvaluationStrategy;\n  extends: string[];\n  policies: Policy[];\n}\n\n`
  + `export const runtimePolicyPacks: Record<string, RuntimePolicyPack> = ${JSON.stringify(packs, null, 2)};\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current !== source) {
    process.stderr.write("Generated runtime policies are stale. Run: npx tsx scripts/compile-runtime-policies.ts\n");
    process.exitCode = 1;
  }
} else {
  await writeFile(output, source);
  process.stdout.write(`Wrote ${output}\n`);
}
